### ISSUE TITLE
Ensure that tests terminate

### ISSUE THREAD

**Issue by thomashoneyman** [purescript-node/purescript-node-http#35]
Currently, CI fails (as described in #33) because the the tests leave servers running until they are manually torn down. This results in timeout failures as in [this failed run](https://github.com/purescript-node/purescript-node-http/actions/runs/481146257). We should fix the tests so that they terminate.

**Comment by VFabricio** [comment]
As I mentioned in #33, it is awkward to torn down the servers given how the tests are currently written. I could take a shot at fixing them, but I'd like to understand a bit better why they are structured like that, because there may be some context I'm not aware of. For the most part, they don't really run any assertions and simply print results to be inspected manually. When something is actually asserted, it uses `unsafeCrashWith` to simply kill the process. What is the rationale for doing things like that? Would it be possible to use a test runner like [purescript-spec](https://purescript-spec.github.io/purescript-spec/) instead?

**Comment by hdgarrood** [comment]
I think the idea with these tests might have been that you run `npm test` to start server processes and then test them manually (e.g. by loading pages in your browser).

**Comment by VFabricio** [comment]
Sounds like a sensible thing to do, but then we would need separate tests suitable for CI, right?

**Comment by hdgarrood** [comment]
Yes; I wouldn't mind replacing them with tests which are suitable for CI, actually.

**Comment by jamesdbrock** [comment]
I'm working on this in #45

**Comment by JordanMartinez** [comment]
Closed by #48
